---
# build.yml

- name: Build Configurations and Documentation # (1)!
  hosts: FABRIC
  gather_facts: false
  tasks:

    - name: Pull Repo from SCM
      ansible.scm.git_retrieve:
        origin:
          url: "{{ git_url }}"
          token: "{{ git_token }}"
        parent_directory: "{{ git_dir }}"
      register: _repo
      run_once: true
      check_mode: false

    - name: Generate AVD Structured Configurations and Fabric Documentation # (2)!
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Device Configurations and Documentation # (3)!
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Push Build Design to SCM 
      ansible.scm.git_publish:
        path: "{{ _repo['path'] }}"
        commit:
          message: "Ansible commit"
        remove: true
        # token: "{{ git_token }}"
      run_once: true
      check_mode: false
