---
# file and storage handling
git_url: "https://github.com/maxrainer/ansible-avd-sot.git"
git_dir: ./tmp
git_branch: main
git_tag_name: "none"
git_tag: ""

root_dir: ./tmp/ansible-avd-sot

custom_templates:
  - ssh.j2

management_eapi:
  enable_http: true
  enable_https: true